security:
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "bcrypt"

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
    app_admin_provider:
      entity:
        class: App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    user:
      pattern: ^/profile
      provider: app_user_provider
      custom_authenticator: App\Security\UserAuthenticator
      logout:
        path: app_logout
    admin:
      pattern: ^/admin
      provider: app_admin_provider
      custom_authenticator: App\Security\AdminAuthenticator
      logout:
        path: admin_logout

  access_control:
    # - { path: ^/admin, roles: ROLE_ADMIN }
    # - { path: ^/profile, roles: ROLE_USER }

when@test:
  security:
    password_hashers:
      Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
        algorithm: auto
        cost: 4 # Lowest possible value for bcrypt
        time_cost: 3 # Lowest possible value for argon
        memory_cost: 10 # Lowest possible value for argon
